// Writes src/index.ts from whatever buf generated.
//
// The barrel is the package's public surface, and hand-maintaining it means a new
// .proto compiles, typechecks, and then fails at bundle time with a missing export.
// Generating it makes that impossible.
import { readdir, writeFile } from "node:fs/promises"
import { join, relative, sep } from "node:path"

const root = new URL("..", import.meta.url).pathname
const genDir = join(root, "src", "gen")

/** Every generated module, deepest-first, as posix paths relative to src/. */
async function generatedModules(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const found = []
  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      found.push(...(await generatedModules(full)))
    } else if (entry.name.endsWith("_pb.ts")) {
      found.push(relative(join(root, "src"), full).split(sep).join("/"))
    }
  }
  return found.sort()
}

const modules = await generatedModules(genDir)
const body = [
  "// Generated by scripts/write-barrel.mjs — do not edit.",
  "//",
  "// Nooks' generated API client. Everything under gen/ comes from proto/ via",
  "// `pnpm generate`; this file is the surface the rest of the monorepo imports.",
  "",
  ...modules.map((module) => `export * from "./${module.replace(/\.ts$/, "")}"`),
  "",
].join("\n")

await writeFile(join(root, "src", "index.ts"), body)
console.log(`wrote src/index.ts with ${modules.length} module(s)`)
