// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file nook/api/v1/instance_service.proto (package nook.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nook/api/v1/instance_service.proto.
 */
export const file_nook_api_v1_instance_service: GenFile = /*@__PURE__*/
  fileDesc("CiJub29rL2FwaS92MS9pbnN0YW5jZV9zZXJ2aWNlLnByb3RvEgtub29rLmFwaS52MSIUChJHZXRJbnN0YW5jZVJlcXVlc3QiYAoTR2V0SW5zdGFuY2VSZXNwb25zZRIMCgRuYW1lGAEgASgJEg8KB3ZlcnNpb24YAiABKAkSEwoLbmVlZHNfc2V0dXAYAyABKAgSFQoNcHVibGljX3NpZ251cBgEIAEoCDJjCg9JbnN0YW5jZVNlcnZpY2USUAoLR2V0SW5zdGFuY2USHy5ub29rLmFwaS52MS5HZXRJbnN0YW5jZVJlcXVlc3QaIC5ub29rLmFwaS52MS5HZXRJbnN0YW5jZVJlc3BvbnNlQqwBCg9jb20ubm9vay5hcGkudjFCFEluc3RhbmNlU2VydmljZVByb3RvUAFaNWdpdGh1Yi5jb20vaG9zaG9tb2gvbm9va3MvcHJvdG8vZ2VuL25vb2svYXBpL3YxO2FwaXYxogIDTkFYqgILTm9vay5BcGkuVjHKAgtOb29rXEFwaVxWMeICF05vb2tcQXBpXFYxXEdQQk1ldGFkYXRh6gINTm9vazo6QXBpOjpWMWIGcHJvdG8z");

/**
 * @generated from message nook.api.v1.GetInstanceRequest
 */
export type GetInstanceRequest = Message<"nook.api.v1.GetInstanceRequest"> & {
};

/**
 * Describes the message nook.api.v1.GetInstanceRequest.
 * Use `create(GetInstanceRequestSchema)` to create a new message.
 */
export const GetInstanceRequestSchema: GenMessage<GetInstanceRequest> = /*@__PURE__*/
  messageDesc(file_nook_api_v1_instance_service, 0);

/**
 * @generated from message nook.api.v1.GetInstanceResponse
 */
export type GetInstanceResponse = Message<"nook.api.v1.GetInstanceResponse"> & {
  /**
   * The mutable display label chosen at first run, e.g. "Brunnen Street". Empty
   * until first run completes.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The build of Nook that is running, e.g. "1.0.2".
   *
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * True until the first Admin exists. The app shows first run rather than sign in.
   *
   * @generated from field: bool needs_setup = 3;
   */
  needsSetup: boolean;

  /**
   * When false, every account starts as a join request an Admin approves.
   *
   * @generated from field: bool public_signup = 4;
   */
  publicSignup: boolean;
};

/**
 * Describes the message nook.api.v1.GetInstanceResponse.
 * Use `create(GetInstanceResponseSchema)` to create a new message.
 */
export const GetInstanceResponseSchema: GenMessage<GetInstanceResponse> = /*@__PURE__*/
  messageDesc(file_nook_api_v1_instance_service, 1);

/**
 * InstanceService reports what this copy of Nook is and how it is configured.
 *
 * @generated from service nook.api.v1.InstanceService
 */
export const InstanceService: GenService<{
  /**
   * GetInstance returns the public profile of this Instance. It is reachable without
   * authentication because the sign-in page and the Public list both need it before
   * anyone has signed in.
   *
   * @generated from rpc nook.api.v1.InstanceService.GetInstance
   */
  getInstance: {
    methodKind: "unary";
    input: typeof GetInstanceRequestSchema;
    output: typeof GetInstanceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_nook_api_v1_instance_service, 0);

